container: Fix NNS contract call for domain name registration
Defect of 1339e1b586756dd3b83a1db28b735bc580998a35. Previously,
container was passed instead of its ID causing:
```
exception: at instruction 3103 (THROW): unhandled exception: "invalid record data"
```

This fixes `addRecord` call argument. Corresponding test is added also.

Refs #484.

Signed-off-by: Leonard Lyubich <leonard@morphbits.io>